name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: tar
      run: cd dist && tar -czvf exercises.tar.gz ./*
    - uses: actions/upload-artifact@v3
      with:
        name: exercises
        path: dist/exercises.tar.gz

